//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhapLoai
    {
        public string MaNK { get; set; }
        public int MaLoaiVT { get; set; }
        public Nullable<short> Soluong { get; set; }
    }
}
