//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietXuatKho
    {
        public string MaXK { get; set; }
        public string MaVT { get; set; }
        public Nullable<short> Soluong { get; set; }
        public Nullable<float> DongiaBan { get; set; }
        public Nullable<float> Giamgia { get; set; }
    
        public virtual XuatKho XuatKho { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
