//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHVT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonKho
    {
        public string MaVT { get; set; }
        public string NgayLap { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> GiaXuat { get; set; }
        public Nullable<int> SLNhap { get; set; }
        public Nullable<int> SLXuat { get; set; }
        public Nullable<int> SLCuoi { get; set; }
    
        public virtual VatTu VatTu { get; set; }
    }
}
